[service_group]
metric_collection_rate = 10
name = 'name goes here'

[[services]]
service_name = 'employee-service'
container_name = 'es1'
endpoint = 'http://localhost:9000/employee-service'

[[services.resources]]
path = '/getData'
method = 'GET'

[[services.resources]]
path = '/index'
method = 'GET'
payload = 'sampleJSON'

[[services]]
service_name = 'another-employee-service'
container_name = 'es2'
endpoint = 'http://localhost:9100/employee-service'

[[services.resources]]
path = '/getData'
method = 'GET'
