[service_group]
name = "name goes here"
metric_collection_rate = 10

[[services]]
container_name = "happy_einstein"
endpoint = "endpoint goes here"

[[services]]
container_name = "mysql5725"
endpoint = "endpoint goes here"
